title: PSC Chicago Member Spotlight
description: Q&A with PSC members doing great things
theme: jekyll-theme-cayman
tags: Join the Pre-Sales Collective!
github:
  repository_url: https://page.presalescollective.com/new-member-sign-up